# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      Image: 'alpine:3.12'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: CmdLine@2
      inputs:
        script: sh test.sh
        workingDirectory: $(Build.SourcesDirectory)
      displayName: Run Load test

    - task: PublishPipelineArtifact@1
      displayName: Publish JMeter Report
      inputs:
        targetPath: $(Build.SourcesDirectory)/**report
        artifact: jmeter