trigger: none

jobs:
  - job: Test
    timeoutInMinutes: 360
    cancelTimeoutInMinutes: 3
    pool: 'Azure Pipelines'
    steps :
    - task: CmdLine@2
      inputs:
        script: sh build.sh
        workingDirectory: $(Build.SourcesDirectory)/TestFiles
      displayName: Run Load test